### ISSUE TITLE
Multi-threaded print

### ISSUE THREAD

**Issue by colinmollenhour** [bezzad/PdfiumViewer#12]
Is it possible to somehow do the rendering to print a multi-page PDF using multiple threads - e.g. separate chunks of pages for each thread? I'm not very experienced with C# and threads but am trying to find a way to speed up printing for large jobs (e.g. 500+ pages). Somehow Adobe Acrobat is way faster than our print program which uses Pdfium.. Your thoughts would be much appreciated!

**Comment by majkimester** [comment]
The underlying Pdfium library is not thread safe, so it is not possible to call more rendering task parallel.

**Comment by colinmollenhour** [comment]
Great to know, thanks for the info @majkimester !
