### ISSUE TITLE
.NET 5 support

### ISSUE THREAD

**Issue by simusr2** [bezzad/PdfiumViewer#4]
Hi, I'm trying to use PdfiumViewer as library in a .NET 5 project but Visual Studio says that is not compatible.

Have you any info about .NET 5 support?

Thanks!

**Comment by bezzad** [comment]
Hi,
I try to fix this issue as soon as possible. Thanks for your feedback.

**Comment by bezzad** [comment]
Please check new version 1.0.6 to solve this problem.

**Comment by simusr2** [comment]
Thanks for your reply!

I tried this new version and it works but when i installed pdfium.dll was not added to project.
I copied it manually from 1.0.5 version!

**Comment by bezzad** [comment]
Wow! I check that, but `Pdfium.dll` was a dependency of my project!
